import type { NotificationChannel, NotificationPriority } from '@prisma/client';

export interface DefaultTemplateEntry {
  code: string;
  name: string;
  subject?: string;
  body: string;
  channels: NotificationChannel[];
  priority: NotificationPriority;
  variables: string[];
  sensitiveFields: string[];
  category: string;
  triggerEvent: string;
  recipientRole: string;
}

/**
 * 24-entry default template catalogue. Each entry produces one NotificationTemplate
 * row per channel (and a matching NotificationRule row) per tenant on seeding.
 */
export const DEFAULT_CATALOGUE: DefaultTemplateEntry[] = [
  {
    code: 'LEAVE_APPLICATION',
    name: 'New Leave Request',
    subject: 'New Leave Request from {{employee_name}}',
    body: '{{employee_name}} requested {{leave_days}} days of leave from {{from_date}} to {{to_date}}.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['employee_name', 'leave_days', 'from_date', 'to_date'],
    sensitiveFields: [],
    category: 'LEAVE_APPROVAL',
    triggerEvent: 'LEAVE_APPLICATION',
    recipientRole: 'APPROVER',
  },
  {
    code: 'LEAVE_APPROVED',
    name: 'Leave Approved',
    subject: 'Your leave request has been approved',
    body: 'Your leave request for {{leave_days}} days has been approved.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['leave_days'],
    sensitiveFields: [],
    category: 'LEAVE_STATUS',
    triggerEvent: 'LEAVE_APPROVED',
    recipientRole: 'REQUESTER',
  },
  {
    code: 'LEAVE_REJECTED',
    name: 'Leave Rejected',
    subject: 'Your leave request has been rejected',
    body: 'Your leave request was rejected. Reason: {{reason}}',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['reason'],
    sensitiveFields: [],
    category: 'LEAVE_STATUS',
    triggerEvent: 'LEAVE_REJECTED',
    recipientRole: 'REQUESTER',
  },
  {
    code: 'ATTENDANCE_REGULARIZATION',
    name: 'Attendance Regularization',
    subject: 'Attendance Regularization Request',
    body: '{{employee_name}} requested attendance regularization for {{date}}.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['employee_name', 'date'],
    sensitiveFields: [],
    category: 'ATTENDANCE_APPROVAL',
    triggerEvent: 'ATTENDANCE_REGULARIZATION',
    recipientRole: 'APPROVER',
  },
  {
    code: 'GEOFENCE_VIOLATION',
    name: 'Geofence Violation Warning',
    subject: '{{employee_name}} checked {{action}} outside geofence',
    body: '{{employee_name}} checked {{action}} outside the designated area at {{location_name}} on {{date}}.',
    channels: ['PUSH', 'IN_APP'],
    priority: 'HIGH',
    variables: ['employee_name', 'date', 'action', 'location_name'],
    sensitiveFields: [],
    category: 'ATTENDANCE',
    triggerEvent: 'GEOFENCE_VIOLATION',
    recipientRole: 'MANAGER',
  },
  {
    code: 'ATTENDANCE_REGULARIZED',
    name: 'Attendance Regularized',
    body: 'Your attendance regularization for {{date}} was approved.',
    channels: ['PUSH', 'IN_APP'],
    priority: 'MEDIUM',
    variables: ['date'],
    sensitiveFields: [],
    category: 'ATTENDANCE_STATUS',
    triggerEvent: 'ATTENDANCE_REGULARIZED',
    recipientRole: 'REQUESTER',
  },
  {
    code: 'OVERTIME_CLAIM',
    name: 'Overtime Claim',
    subject: 'Overtime Claim from {{employee_name}}',
    body: '{{employee_name}} submitted an overtime claim for {{hours}} hours on {{date}}.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['employee_name', 'hours', 'date'],
    sensitiveFields: [],
    category: 'OVERTIME_APPROVAL',
    triggerEvent: 'OVERTIME_CLAIM',
    recipientRole: 'APPROVER',
  },
  {
    code: 'OVERTIME_AUTO_DETECTED',
    name: 'Overtime Auto-Detected',
    subject: 'Overtime Detected — {{date}}',
    body: 'The system detected {{hours}} hours of overtime on {{date}}. A request has been created for approval.',
    channels: ['PUSH', 'IN_APP'],
    priority: 'LOW',
    variables: ['employee_name', 'date', 'hours', 'multiplier_source'],
    sensitiveFields: [],
    category: 'OVERTIME',
    triggerEvent: 'OVERTIME_AUTO_DETECTED',
    recipientRole: 'SELF',
  },
  {
    code: 'COMP_OFF_GRANTED',
    name: 'Compensatory Off Credited',
    subject: 'Compensatory Off Credited',
    body: '{{days}} day(s) of compensatory off have been credited for your overtime on {{date}}. Your current balance is {{balance}} day(s).',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['employee_name', 'days', 'date', 'expires_at', 'balance'],
    sensitiveFields: [],
    category: 'OVERTIME',
    triggerEvent: 'COMP_OFF_GRANTED',
    recipientRole: 'SELF',
  },
  {
    code: 'REIMBURSEMENT',
    name: 'Reimbursement Request',
    subject: 'Reimbursement Request',
    body: '{{employee_name}} requested reimbursement of {{amount}} for {{category}}.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['employee_name', 'amount', 'category'],
    sensitiveFields: ['amount'],
    category: 'REIMBURSEMENT_APPROVAL',
    triggerEvent: 'REIMBURSEMENT',
    recipientRole: 'APPROVER',
  },
  {
    code: 'REIMBURSEMENT_APPROVED',
    name: 'Reimbursement Approved',
    subject: 'Reimbursement Approved',
    body: 'Your reimbursement request for {{amount}} has been approved.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['amount'],
    sensitiveFields: ['amount'],
    category: 'REIMBURSEMENT_STATUS',
    triggerEvent: 'REIMBURSEMENT_APPROVED',
    recipientRole: 'REQUESTER',
  },
  {
    code: 'LOAN_APPLICATION',
    name: 'Loan Application',
    subject: 'Loan Application from {{employee_name}}',
    body: '{{employee_name}} applied for a loan of {{amount}}.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['employee_name', 'amount'],
    sensitiveFields: ['amount'],
    category: 'LOAN_APPROVAL',
    triggerEvent: 'LOAN_APPLICATION',
    recipientRole: 'APPROVER',
  },
  {
    code: 'LOAN_APPROVED',
    name: 'Loan Approved',
    subject: 'Your loan has been approved',
    body: 'Your loan application for {{amount}} has been approved.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'HIGH',
    variables: ['amount'],
    sensitiveFields: ['amount'],
    category: 'LOAN_STATUS',
    triggerEvent: 'LOAN_APPROVED',
    recipientRole: 'REQUESTER',
  },
  {
    code: 'WFH_REQUEST',
    name: 'Work From Home Request',
    body: '{{employee_name}} requested WFH for {{date_range}}.',
    channels: ['PUSH', 'IN_APP'],
    priority: 'MEDIUM',
    variables: ['employee_name', 'date_range'],
    sensitiveFields: [],
    category: 'WFH_APPROVAL',
    triggerEvent: 'WFH_REQUEST',
    recipientRole: 'APPROVER',
  },
  {
    code: 'SHIFT_CHANGE',
    name: 'Shift Change Request',
    body: '{{employee_name}} requested a shift change.',
    channels: ['PUSH', 'IN_APP'],
    priority: 'MEDIUM',
    variables: ['employee_name'],
    sensitiveFields: [],
    category: 'SHIFT_APPROVAL',
    triggerEvent: 'SHIFT_CHANGE',
    recipientRole: 'APPROVER',
  },
  {
    code: 'PROFILE_UPDATE',
    name: 'Profile Update Request',
    subject: 'Profile Update from {{employee_name}}',
    body: '{{employee_name}} submitted a profile update.',
    channels: ['IN_APP', 'EMAIL'],
    priority: 'LOW',
    variables: ['employee_name'],
    sensitiveFields: [],
    category: 'PROFILE',
    triggerEvent: 'PROFILE_UPDATE',
    recipientRole: 'HR',
  },
  {
    code: 'IT_DECLARATION',
    name: 'IT Declaration Submitted',
    subject: 'IT Declaration Submitted',
    body: '{{employee_name}} submitted their IT declaration for FY {{fy}}.',
    channels: ['IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['employee_name', 'fy'],
    sensitiveFields: [],
    category: 'IT_DECLARATION',
    triggerEvent: 'IT_DECLARATION',
    recipientRole: 'HR',
  },
  {
    code: 'RESIGNATION',
    name: 'Resignation Submitted',
    subject: 'Resignation from {{employee_name}}',
    body: '{{employee_name}} has submitted a resignation. Last working day: {{last_day}}.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'HIGH',
    variables: ['employee_name', 'last_day'],
    sensitiveFields: [],
    category: 'RESIGNATION',
    triggerEvent: 'RESIGNATION',
    recipientRole: 'HR',
  },
  {
    code: 'PAYROLL_APPROVAL',
    name: 'Payroll Approval Pending',
    subject: 'Payroll for {{month_year}} Awaiting Approval',
    body: 'Payroll for {{month_year}} is awaiting your approval.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'HIGH',
    variables: ['month_year'],
    sensitiveFields: [],
    category: 'PAYROLL_APPROVAL',
    triggerEvent: 'PAYROLL_APPROVAL',
    recipientRole: 'APPROVER',
  },
  {
    code: 'PAYSLIP_PUBLISHED',
    name: 'Payslip Available',
    subject: 'Your payslip for {{month_year}} is now available',
    body: 'Your payslip for {{month_year}} is now available.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'HIGH',
    variables: ['month_year'],
    sensitiveFields: [],
    category: 'PAYROLL',
    triggerEvent: 'PAYSLIP_PUBLISHED',
    recipientRole: 'EMPLOYEE',
  },
  {
    code: 'SALARY_CREDITED',
    name: 'Salary Credited',
    body: 'Your salary of {{amount}} for {{month_year}} has been credited.',
    channels: ['PUSH', 'IN_APP'],
    priority: 'CRITICAL',
    variables: ['amount', 'month_year'],
    sensitiveFields: ['amount'],
    category: 'PAYROLL',
    triggerEvent: 'SALARY_CREDITED',
    recipientRole: 'EMPLOYEE',
  },
  {
    code: 'INTERVIEW_SCHEDULED',
    name: 'Interview Scheduled',
    subject: 'Interview Scheduled: {{candidate_name}}',
    body: 'You are scheduled as a panelist for {{candidate_name}} on {{interview_date}}.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['candidate_name', 'interview_date'],
    sensitiveFields: [],
    category: 'RECRUITMENT',
    triggerEvent: 'INTERVIEW_SCHEDULED',
    recipientRole: 'APPROVER',
  },
  {
    code: 'TRAINING_NOMINATION',
    name: 'Training Nomination',
    subject: 'Training Nomination: {{training_name}}',
    body: 'You have been nominated for "{{training_name}}".',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['training_name'],
    sensitiveFields: [],
    category: 'TRAINING',
    triggerEvent: 'TRAINING_NOMINATION',
    recipientRole: 'EMPLOYEE',
  },
  {
    code: 'TRAINING_COMPLETED',
    name: 'Training Completed',
    subject: 'Training Completed',
    body: 'Congratulations! You have completed "{{training_name}}".',
    channels: ['IN_APP', 'EMAIL'],
    priority: 'LOW',
    variables: ['training_name'],
    sensitiveFields: [],
    category: 'TRAINING',
    triggerEvent: 'TRAINING_COMPLETED',
    recipientRole: 'EMPLOYEE',
  },
  {
    code: 'CERTIFICATE_EXPIRING',
    name: 'Certificate Expiring',
    subject: 'Certificate Expiring Soon',
    body: 'Your "{{training_name}}" certificate expires on {{expiry_date}}.',
    channels: ['PUSH', 'IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['training_name', 'expiry_date'],
    sensitiveFields: [],
    category: 'TRAINING',
    triggerEvent: 'CERTIFICATE_EXPIRING',
    recipientRole: 'EMPLOYEE',
  },
  {
    code: 'TICKET_MESSAGE',
    name: 'New Ticket Message',
    body: 'New message on ticket "{{ticket_subject}}"',
    channels: ['PUSH', 'IN_APP'],
    priority: 'MEDIUM',
    variables: ['ticket_subject'],
    sensitiveFields: [],
    category: 'SUPPORT',
    triggerEvent: 'TICKET_MESSAGE',
    recipientRole: 'REQUESTER',
  },
  {
    code: 'PASSWORD_RESET',
    name: 'Password Reset Code',
    subject: 'Your password reset code',
    body: 'Your password reset code is {{reset_code}}. Expires in {{expires_in}}.',
    channels: ['EMAIL', 'PUSH'],
    priority: 'CRITICAL',
    variables: ['reset_code', 'expires_in'],
    sensitiveFields: ['reset_code'],
    category: 'AUTH',
    triggerEvent: 'PASSWORD_RESET',
    recipientRole: 'REQUESTER',
  },
  {
    code: 'NEW_DEVICE_LOGIN',
    name: 'New Device Login',
    subject: 'Security alert: new device login',
    body: 'A new login was detected on {{device_info}} from {{ip_address}} at {{login_time}}. If this wasn\'t you, reset your password immediately.',
    channels: ['EMAIL', 'PUSH', 'IN_APP'],
    priority: 'CRITICAL',
    variables: ['device_info', 'ip_address', 'login_time'],
    sensitiveFields: [],
    category: 'AUTH',
    triggerEvent: 'NEW_DEVICE_LOGIN',
    recipientRole: 'REQUESTER',
  },
  {
    code: 'ACCOUNT_LOCKED',
    name: 'Account Locked',
    subject: 'Security alert: account locked',
    body: 'Your account has been locked due to {{reason}}. Contact your administrator to unlock.',
    channels: ['EMAIL', 'PUSH', 'IN_APP'],
    priority: 'CRITICAL',
    variables: ['reason'],
    sensitiveFields: [],
    category: 'AUTH',
    triggerEvent: 'ACCOUNT_LOCKED',
    recipientRole: 'REQUESTER',
  },

  // ── Announcements ───────────────────────────────────────────────────
  {
    code: 'ANNOUNCEMENT',
    name: 'Company Announcement',
    subject: '{{title}}',
    body: '{{body}}',
    channels: ['IN_APP', 'PUSH', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['title', 'body', 'sent_by', 'image_url'],
    sensitiveFields: [],
    category: 'ANNOUNCEMENTS',
    triggerEvent: 'ANNOUNCEMENT',
    recipientRole: 'ALL',
  },

  // ── Cron-driven informational templates ─────────────────────────────
  {
    code: 'BIRTHDAY',
    name: 'Happy Birthday',
    body: 'Happy Birthday, {{employee_name}}! Wishing you a wonderful year ahead.',
    channels: ['IN_APP', 'PUSH'],
    priority: 'LOW',
    variables: ['employee_name'],
    sensitiveFields: [],
    category: 'BIRTHDAY_ANNIVERSARY',
    triggerEvent: 'BIRTHDAY',
    recipientRole: 'EMPLOYEE',
  },
  {
    code: 'WORK_ANNIVERSARY',
    name: 'Work Anniversary',
    body: 'Congratulations, {{employee_name}}! Today marks {{years_of_service}} year(s) with us. Thank you for your dedication.',
    channels: ['IN_APP', 'PUSH'],
    priority: 'LOW',
    variables: ['employee_name', 'years_of_service'],
    sensitiveFields: [],
    category: 'BIRTHDAY_ANNIVERSARY',
    triggerEvent: 'WORK_ANNIVERSARY',
    recipientRole: 'EMPLOYEE',
  },
  {
    code: 'HOLIDAY_REMINDER',
    name: 'Upcoming Holiday',
    body: '{{holiday_name}} is coming up on {{holiday_date}} ({{days_until}} day(s) away). Plan your schedule accordingly.',
    channels: ['IN_APP'],
    priority: 'LOW',
    variables: ['holiday_name', 'holiday_date', 'days_until'],
    sensitiveFields: [],
    category: 'ANNOUNCEMENTS',
    triggerEvent: 'HOLIDAY_REMINDER',
    recipientRole: 'ALL',
  },
  {
    code: 'PROBATION_END_REMINDER',
    name: 'Probation Ending Soon',
    subject: 'Probation Review Required: {{employee_name}}',
    body: '{{employee_name}} probation period ends on {{probation_end_date}}. Please schedule a review meeting.',
    channels: ['IN_APP', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['employee_name', 'probation_end_date'],
    sensitiveFields: [],
    category: 'EMPLOYEE_LIFECYCLE',
    triggerEvent: 'PROBATION_END_REMINDER',
    recipientRole: 'MANAGER',
  },
  {
    code: 'CERTIFICATE_EXPIRING',
    name: 'Certificate Expiring Soon',
    subject: 'Your {{training_name}} certificate is expiring',
    body: 'Your certificate for "{{training_name}}" expires on {{expiry_date}}. Please renew before it lapses.',
    channels: ['IN_APP', 'EMAIL', 'PUSH'],
    priority: 'MEDIUM',
    variables: ['training_name', 'expiry_date'],
    sensitiveFields: [],
    category: 'TRAINING',
    triggerEvent: 'CERTIFICATE_EXPIRING',
    recipientRole: 'EMPLOYEE',
  },
  {
    code: 'TRAINING_SESSION_UPCOMING',
    name: 'Training Session Tomorrow',
    body: 'Your training session "{{training_name}}" is scheduled for {{session_date}} at {{session_time}}. See you there!',
    channels: ['IN_APP', 'PUSH', 'EMAIL'],
    priority: 'MEDIUM',
    variables: ['training_name', 'session_date', 'session_time'],
    sensitiveFields: [],
    category: 'TRAINING',
    triggerEvent: 'TRAINING_SESSION_UPCOMING',
    recipientRole: 'EMPLOYEE',
  },
];
