// ─── Enterprise Excel Export Engine ───
import * as ExcelJS from 'exceljs';

// ─── Style Constants ───
export const HEADER_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FF4F46E5' },
};

export const HEADER_FONT: Partial<ExcelJS.Font> = {
  color: { argb: 'FFFFFFFF' },
  bold: true,
  name: 'Calibri',
  size: 11,
};

export const TITLE_FONT: Partial<ExcelJS.Font> = {
  bold: true,
  name: 'Calibri',
  size: 14,
};

export const SUBTITLE_FONT: Partial<ExcelJS.Font> = {
  bold: true,
  color: { argb: 'FF6B7280' },
  name: 'Calibri',
  size: 11,
};

export const TOTAL_ROW_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFF3F4F6' },
};

export const ALT_ROW_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFF9FAFB' },
};

export const RED_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFFEE2E2' },
};

export const GREEN_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFD1FAE5' },
};

export const AMBER_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFFEF3C7' },
};

export const CURRENCY_FORMAT = '₹#,##0.00';
export const PERCENT_FORMAT = '0.0%';
export const DATE_FORMAT = 'DD-MMM-YYYY';

// ─── Interfaces ───
export interface SheetColumn {
  header: string;
  key: string;
  width?: number;
  format?: 'currency' | 'percentage' | 'date' | 'number' | 'text';
  conditionalFormat?: 'red-if-negative' | 'green-if-positive' | 'status';
}

export interface ReportSheet {
  name: string;
  columns: SheetColumn[];
  rows: Record<string, unknown>[];
  totalsRow?: Record<string, unknown>;
  freezeRow?: number;
}

export interface ReportConfig {
  companyName: string;
  reportTitle: string;
  period: string;
  sheets: ReportSheet[];
}

// ─── Helper: column number to letter (1=A, 27=AA) ───
export function columnLetter(colNum: number): string {
  let result = '';
  let n = colNum;
  while (n > 0) {
    const remainder = (n - 1) % 26;
    result = String.fromCharCode(65 + remainder) + result;
    n = Math.floor((n - 1) / 26);
  }
  return result;
}

// ─── Format helpers ───
function getNumFormat(format?: SheetColumn['format']): string | undefined {
  switch (format) {
    case 'currency':
      return CURRENCY_FORMAT;
    case 'percentage':
      return PERCENT_FORMAT;
    case 'date':
      return DATE_FORMAT;
    case 'number':
      return '#,##0';
    default:
      return undefined;
  }
}

function applyConditionalFormat(
  cell: ExcelJS.Cell,
  value: unknown,
  conditionalFormat?: SheetColumn['conditionalFormat'],
): void {
  if (!conditionalFormat) return;

  const numVal = typeof value === 'number' ? value : Number(value);

  switch (conditionalFormat) {
    case 'red-if-negative':
      if (!isNaN(numVal) && numVal < 0) {
        cell.fill = RED_FILL;
      }
      break;
    case 'green-if-positive':
      if (!isNaN(numVal) && numVal > 0) {
        cell.fill = GREEN_FILL;
      }
      break;
    case 'status': {
      const strVal = String(value ?? '').toUpperCase();
      if (['ACTIVE', 'APPROVED', 'COMPLETED', 'FILED', 'COMPLIANT', 'PRESENT'].includes(strVal)) {
        cell.fill = GREEN_FILL;
      } else if (['PENDING', 'DRAFT', 'IN_PROGRESS', 'HALF_DAY', 'LATE'].includes(strVal)) {
        cell.fill = AMBER_FILL;
      } else if (['REJECTED', 'OVERDUE', 'ABSENT', 'EXITED', 'SUSPENDED', 'NON_COMPLIANT'].includes(strVal)) {
        cell.fill = RED_FILL;
      }
      break;
    }
  }
}

// ─── Main Export Function ───
export async function generateExcelReport(config: ReportConfig): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Avy ERP';
  workbook.created = new Date();

  for (const sheet of config.sheets) {
    const ws = workbook.addWorksheet(sheet.name, {
      pageSetup: {
        orientation: 'landscape',
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
        paperSize: 9, // A4
      },
      headerFooter: {
        oddFooter: `&L&"Calibri,Regular"&8Generated by Avy ERP | ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}&R&"Calibri,Regular"&8Page &P of &N`,
      },
    });

    const colCount = sheet.columns.length;
    const lastColLetter = columnLetter(colCount);

    // Row 1: Company name (merged, title font)
    ws.mergeCells(`A1:${lastColLetter}1`);
    const titleCell = ws.getCell('A1');
    titleCell.value = config.companyName;
    titleCell.font = TITLE_FONT;
    titleCell.alignment = { horizontal: 'left', vertical: 'middle' };
    ws.getRow(1).height = 24;

    // Row 2: Report title + sheet name (subtitle)
    ws.mergeCells(`A2:${lastColLetter}2`);
    const subtitleCell = ws.getCell('A2');
    subtitleCell.value = `${config.reportTitle} — ${sheet.name}`;
    subtitleCell.font = SUBTITLE_FONT;
    subtitleCell.alignment = { horizontal: 'left', vertical: 'middle' };
    ws.getRow(2).height = 20;

    // Row 3: Period (small gray)
    ws.mergeCells(`A3:${lastColLetter}3`);
    const periodCell = ws.getCell('A3');
    periodCell.value = `Period: ${config.period}`;
    periodCell.font = { name: 'Calibri', size: 9, color: { argb: 'FF9CA3AF' } };
    periodCell.alignment = { horizontal: 'left', vertical: 'middle' };

    // Row 4: Empty spacer
    ws.getRow(4).height = 8;

    // Row 5: Column headers
    const headerRow = ws.getRow(5);
    sheet.columns.forEach((col, idx) => {
      const cell = headerRow.getCell(idx + 1);
      cell.value = col.header;
      cell.fill = HEADER_FILL;
      cell.font = HEADER_FONT;
      cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
      cell.border = {
        bottom: { style: 'thin', color: { argb: 'FF4338CA' } },
      };

      // Set column width
      ws.getColumn(idx + 1).width = col.width ?? 15;
    });
    headerRow.height = 22;

    // Row 6+: Data rows with alternating colors, formatting, conditional formatting
    sheet.rows.forEach((row, rowIdx) => {
      const dataRow = ws.getRow(6 + rowIdx);
      const isAlt = rowIdx % 2 === 1;

      sheet.columns.forEach((col, colIdx) => {
        const cell = dataRow.getCell(colIdx + 1);
        const value = row[col.key];
        cell.value = value as ExcelJS.CellValue;

        // Number format
        const numFmt = getNumFormat(col.format);
        if (numFmt) {
          cell.numFmt = numFmt;
        }

        // Alternating row fill
        if (isAlt) {
          cell.fill = ALT_ROW_FILL;
        }

        // Conditional formatting (overrides alt row fill)
        applyConditionalFormat(cell, value, col.conditionalFormat);

        // Alignment
        cell.alignment = {
          horizontal: col.format === 'currency' || col.format === 'number' || col.format === 'percentage'
            ? 'right'
            : 'left',
          vertical: 'middle',
        };

        cell.font = { name: 'Calibri', size: 10 };
      });
    });

    // Totals row (if provided)
    if (sheet.totalsRow) {
      const totalsRowNum = 6 + sheet.rows.length;
      const tRow = ws.getRow(totalsRowNum);

      sheet.columns.forEach((col, colIdx) => {
        const cell = tRow.getCell(colIdx + 1);
        const value = sheet.totalsRow![col.key];
        cell.value = value as ExcelJS.CellValue;
        cell.fill = TOTAL_ROW_FILL;
        cell.font = { name: 'Calibri', size: 10, bold: true };
        cell.border = {
          top: { style: 'thin', color: { argb: 'FFD1D5DB' } },
          bottom: { style: 'double', color: { argb: 'FF6B7280' } },
        };

        const numFmt = getNumFormat(col.format);
        if (numFmt) {
          cell.numFmt = numFmt;
        }

        cell.alignment = {
          horizontal: col.format === 'currency' || col.format === 'number' || col.format === 'percentage'
            ? 'right'
            : 'left',
          vertical: 'middle',
        };
      });
    }

    // Auto-filters on all data columns
    const lastDataRow = 5 + sheet.rows.length + (sheet.totalsRow ? 1 : 0);
    ws.autoFilter = {
      from: { row: 5, column: 1 },
      to: { row: lastDataRow, column: colCount },
    };

    // Frozen panes at header row
    const freezeRow = sheet.freezeRow ?? 6;
    ws.views = [
      {
        state: 'frozen',
        xSplit: 0,
        ySplit: freezeRow - 1,
        topLeftCell: `A${freezeRow}`,
        activeCell: `A${freezeRow}`,
      },
    ];
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
