import type { ReportSheet, SheetColumn } from '../../excel-exporter';
import type { ReportDataset } from './types';
import { MONTH_NAMES } from './types';

// ─── Column layout ───
const columns: SheetColumn[] = [
  { header: 'Metric',  key: 'metric',  width: 30 },
  { header: 'Value',   key: 'value',   width: 20 },
  { header: '',        key: 'col3',    width: 20 },
  { header: '',        key: 'col4',    width: 15 },
  { header: '',        key: 'col5',    width: 15 },
  { header: '',        key: 'col6',    width: 15 },
  { header: '',        key: 'col7',    width: 15 },
  { header: '',        key: 'col8',    width: 15 },
  { header: '',        key: 'col9',    width: 15 },
  { header: '',        key: 'col10',   width: 15 },
];

// ─── Helpers ───
type Row = Record<string, unknown>;

function sectionHeader(label: string): Row {
  return { metric: label, value: '' };
}

function blankRow(): Row {
  return { metric: '' };
}

function kv(metric: string, value: unknown): Row {
  return { metric, value };
}

function pct(numerator: number, denominator: number): string {
  if (denominator === 0) return '0.0%';
  return `${((numerator / denominator) * 100).toFixed(1)}%`;
}

// ─── Main builder ───
export function buildExecutiveSummary(dataset: ReportDataset): ReportSheet {
  const rows: Row[] = [];

  // ── Section 1: Report Metadata ──────────────────────────────────────────
  rows.push(sectionHeader('REPORT METADATA'));
  rows.push(kv('Company',             dataset.companyName));
  rows.push(kv('Report Period',        `${dataset.filters.dateFrom} to ${dataset.filters.dateTo}`));
  rows.push(kv('Report Mode',          dataset.mode));
  rows.push(kv('Generated On',         dataset.generatedAt.toISOString()));
  rows.push(kv('Generated By',         dataset.generatedBy));
  rows.push(kv('Timezone',             dataset.companyTimezone));
  rows.push(kv('Payroll Lock Status',  dataset.payrollRun?.status ?? 'No payroll run'));
  rows.push(kv('Total Employees',      dataset.totalEmployees));
  rows.push(kv('Employees in Scope',   dataset.filteredEmployees));
  rows.push(kv('Total Records',        dataset.records.length));

  // ── Section 2: Attendance KPIs ──────────────────────────────────────────
  rows.push(blankRow());
  rows.push(sectionHeader('ATTENDANCE KPIs'));

  const sc = dataset.statusCounts;

  // Present = raw PRESENT + regularized + late (they are all "present" statuses)
  const presentCount = (sc['PRESENT'] ?? 0) + (sc['LATE'] ?? 0) + (sc['REGULARIZED'] ?? 0);
  const absentCount  = sc['ABSENT']   ?? 0;
  const leaveCount   = sc['ON_LEAVE'] ?? 0;
  const halfCount    = sc['HALF_DAY'] ?? 0;
  const holidayCount = sc['HOLIDAY']  ?? 0;
  const weekOffCount = sc['WEEK_OFF'] ?? 0;
  const lopCount     = sc['LOP']      ?? 0;
  const missingCount = sc['INCOMPLETE'] ?? 0;

  const lateCount      = dataset.records.filter(r => r.isLate && r.shiftSequence <= 1).length;
  const earlyExitCount = dataset.records.filter(r => r.isEarlyExit && r.shiftSequence <= 1).length;

  rows.push(kv('Present Days',     presentCount));
  rows.push(kv('Absent Days',      absentCount));
  rows.push(kv('Leave Days',       leaveCount));
  rows.push(kv('Half Day',         halfCount));
  rows.push(kv('Late Count',       lateCount));
  rows.push(kv('Early Exit Count', earlyExitCount));
  rows.push(kv('Holiday Days',     holidayCount));
  rows.push(kv('Week Off Days',    weekOffCount));
  rows.push(kv('LOP Days',         lopCount));
  rows.push(kv('Missing Punch',    missingCount));

  // ── Section 3: Hours KPIs ───────────────────────────────────────────────
  rows.push(blankRow());
  rows.push(sectionHeader('HOURS KPIs'));

  const totalWorked = dataset.records.filter(r => r.shiftSequence <= 1).reduce((sum, r) => sum + r.workedHours, 0);
  const totalOT     = dataset.records.filter(r => r.shiftSequence <= 1).reduce((sum, r) => sum + r.overtimeHours, 0);
  const avgWorked   = presentCount > 0 ? Math.round((totalWorked / presentCount) * 10) / 10 : 0;

  rows.push(kv('Total Worked Hours',     totalWorked.toFixed(2)));
  rows.push(kv('Total OT Hours',         totalOT.toFixed(2)));
  rows.push(kv('Avg Worked Hours/Day',   avgWorked.toFixed(1)));

  // ── Section 4: Rates ────────────────────────────────────────────────────
  rows.push(blankRow());
  rows.push(sectionHeader('RATES'));

  // Total working days = primary records (exclude sub-sessions, holidays, weekoffs)
  const totalWorkingDayRecords = dataset.records.filter(
    r => r.shiftSequence <= 1 && r.status !== 'HOLIDAY' && r.status !== 'WEEK_OFF',
  ).length;

  const effectivePresent = presentCount + halfCount * 0.5;
  const attendancePct  = pct(effectivePresent, totalWorkingDayRecords);
  const absenteeismPct = pct(absentCount, totalWorkingDayRecords);
  const punctualPct    = presentCount > 0 ? pct(presentCount - lateCount, presentCount) : '0.0%';

  rows.push(kv('Attendance %',   attendancePct));
  rows.push(kv('Absenteeism %',  absenteeismPct));
  rows.push(kv('Punctuality %',  punctualPct));

  // ── Section 5: Multi-month trend (only in multi-month mode) ─────────────
  if (dataset.mode === 'multi-month') {
    rows.push(blankRow());
    rows.push(sectionHeader('MONTH-OVER-MONTH TREND'));

    // Header row for the trend table
    rows.push({
      metric: 'Month',
      value:  'Present',
      col3:   'Absent',
      col4:   'Leave',
      col5:   'Late',
      col6:   'OT Hrs',
      col7:   'Worked Hrs',
      col8:   'Att %',
    });

    // Group records by year-month key
    const monthMap = new Map<string, typeof dataset.records>();
    for (const r of dataset.records) {
      const d = r.date instanceof Date ? r.date : new Date(r.date);
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
      if (!monthMap.has(key)) monthMap.set(key, []);
      monthMap.get(key)!.push(r);
    }

    // Sort months chronologically
    const sortedKeys = [...monthMap.keys()].sort();

    for (const key of sortedKeys) {
      const monthRecords = monthMap.get(key)!;
      const parts = key.split('-');
      const yearStr  = parts[0] ?? key;
      const monthStr = parts[1] ?? '01';
      const monthLabel = `${MONTH_NAMES[parseInt(monthStr, 10) - 1] ?? monthStr} ${yearStr}`;

      const mPresent = monthRecords.filter(
        r => r.status === 'PRESENT' || r.status === 'LATE' || r.status === 'REGULARIZED',
      ).length;
      const mAbsent  = monthRecords.filter(r => r.status === 'ABSENT').length;
      const mLeave   = monthRecords.filter(r => r.status === 'ON_LEAVE').length;
      const mLate    = monthRecords.filter(r => r.isLate).length;
      const mOT      = monthRecords.reduce((s, r) => s + r.overtimeHours, 0);
      const mWorked  = monthRecords.reduce((s, r) => s + r.workedHours, 0);
      const mWorkDay = monthRecords.filter(
        r => r.status !== 'HOLIDAY' && r.status !== 'WEEK_OFF',
      ).length;
      const mAttPct  = pct(mPresent, mWorkDay);

      rows.push({
        metric: monthLabel,
        value:  mPresent,
        col3:   mAbsent,
        col4:   mLeave,
        col5:   mLate,
        col6:   mOT.toFixed(2),
        col7:   mWorked.toFixed(2),
        col8:   mAttPct,
      });
    }
  }

  // ── Section 6: Department Breakdown ────────────────────────────────────
  rows.push(blankRow());
  rows.push(sectionHeader('DEPARTMENT BREAKDOWN'));

  // Table header
  rows.push({
    metric: 'Department',
    value:  'Employees',
    col3:   'Present',
    col4:   'Absent',
    col5:   'Leave',
    col6:   'Late',
    col7:   'OT Hrs',
    col8:   'Worked Hrs',
    col9:   'Att %',
  });

  for (const dept of dataset.deptBreakdown) {
    rows.push({
      metric: dept.department,
      value:  dept.employees,
      col3:   dept.present,
      col4:   dept.absent,
      col5:   dept.leave,
      col6:   dept.late,
      col7:   dept.otHours.toFixed(2),
      col8:   dept.workedHours.toFixed(2),
      col9:   `${dept.attendancePct.toFixed(1)}%`,
    });
  }

  // ── Section 7: Shift Breakdown ──────────────────────────────────────────
  rows.push(blankRow());
  rows.push(sectionHeader('SHIFT BREAKDOWN'));

  // Table header
  rows.push({
    metric: 'Shift',
    value:  'Timing',
    col3:   'Type',
    col4:   'Employees',
    col5:   'Records',
    col6:   'Late',
    col7:   'Late %',
    col8:   'OT Hrs',
    col9:   'Avg Worked',
    col10:  'Att %',
  });

  for (const shift of dataset.shiftBreakdown) {
    rows.push({
      metric: shift.shiftName,
      value:  shift.shiftTiming,
      col3:   shift.shiftType,
      col4:   shift.assignedEmployees,
      col5:   shift.totalRecords,
      col6:   shift.lateCount,
      col7:   `${shift.latePct.toFixed(1)}%`,
      col8:   shift.otHoursTotal.toFixed(2),
      col9:   shift.avgWorkedHours.toFixed(1),
      col10:  `${shift.attendancePct.toFixed(1)}%`,
    });
  }

  return {
    name: 'Executive Summary',
    columns,
    rows,
  };
}
