import type { ReportSheet, SheetColumn } from '../../excel-exporter';
import type { ReportDataset } from './types';

// ─── Column layout ───
const columns: SheetColumn[] = [
  { header: 'Field', key: 'field', width: 35 },
  { header: 'Value', key: 'value', width: 50 },
];

// ─── Main builder ───
export function buildProcessingMetadata(dataset: ReportDataset): ReportSheet {
  const rows: Record<string, unknown>[] = [];

  // ── Section: Report Generation Context ──
  rows.push({ field: '── REPORT GENERATION CONTEXT ──', value: '' });
  rows.push({ field: 'Generated At', value: dataset.generatedAt.toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' }) });
  rows.push({ field: 'Generated By', value: dataset.generatedBy });
  rows.push({ field: 'Report Period', value: `${dataset.filters.dateFrom} to ${dataset.filters.dateTo}` });
  rows.push({ field: 'Report Mode', value: dataset.mode });
  rows.push({ field: 'Timezone', value: dataset.companyTimezone });
  rows.push({ field: 'Filters Applied', value: JSON.stringify(dataset.filters, null, 0) });
  rows.push({ field: 'Employee Scope', value: `${dataset.filteredEmployees} of ${dataset.totalEmployees} employees` });
  rows.push({ field: 'Total Records Processed', value: dataset.records.length });
  rows.push({ field: 'Day Count', value: dataset.dayCount });
  rows.push({ field: '', value: '' }); // spacer

  // ── Section: Attendance Policy ──
  rows.push({ field: '── ATTENDANCE POLICY ──', value: '' });
  const rules = dataset.attendanceRules as Record<string, unknown>;
  rows.push({ field: 'Grace Period', value: `${rules.gracePeriodMinutes ?? '—'} minutes` });
  rows.push({ field: 'Half Day Threshold', value: `${rules.halfDayThresholdHours ?? '—'} hours` });
  rows.push({ field: 'Full Day Threshold', value: `${rules.fullDayThresholdHours ?? '—'} hours` });
  rows.push({ field: 'Max Late Check-in', value: `${rules.maxLateCheckInMinutes ?? '—'} minutes` });
  rows.push({ field: 'Auto Mark Absent If No Punch', value: rules.autoMarkAbsentIfNoPunch ? 'Yes' : 'No' });
  rows.push({ field: 'Auto Half Day Enabled', value: rules.autoHalfDayEnabled ? 'Yes' : 'No' });
  rows.push({ field: 'LOP Auto Deduct', value: rules.lopAutoDeduct ? 'Yes' : 'No' });
  rows.push({ field: 'Late Deduction Type', value: String(rules.lateDeductionType ?? 'NONE') });
  rows.push({ field: 'Early Exit Deduction Type', value: String(rules.earlyExitDeductionType ?? 'NONE') });
  rows.push({ field: 'Working Hours Rounding', value: String(rules.workingHoursRounding ?? 'NONE') });
  rows.push({ field: 'Multiple Shifts Per Day', value: rules.multipleShiftsPerDayEnabled ? 'Yes' : 'No' });
  rows.push({ field: 'Auto Shift Mapping', value: rules.autoShiftMappingEnabled ? 'Yes' : 'No' });
  rows.push({ field: 'Weekly Review Enabled', value: rules.weeklyReviewEnabled ? 'Yes' : 'No' });
  rows.push({ field: '', value: '' }); // spacer

  // ── Section: Overtime Policy ──
  rows.push({ field: '── OVERTIME POLICY ──', value: '' });
  if (dataset.overtimeRules) {
    const ot = dataset.overtimeRules as Record<string, unknown>;
    rows.push({ field: 'Calculation Basis', value: String(ot.calculationBasis ?? '—') });
    rows.push({ field: 'Threshold Minutes', value: `${ot.thresholdMinutes ?? '—'}` });
    rows.push({ field: 'Daily Cap', value: `${ot.dailyCapHours ?? '—'} hours` });
    rows.push({ field: 'Weekly Cap', value: `${ot.weeklyCapHours ?? '—'} hours` });
    rows.push({ field: 'Monthly Cap', value: `${ot.monthlyCapHours ?? '—'} hours` });
    rows.push({ field: 'Approval Required', value: ot.approvalRequired ? 'Yes' : 'No' });
    rows.push({ field: 'Comp Off Enabled', value: ot.compOffEnabled ? 'Yes' : 'No' });
  } else {
    rows.push({ field: 'Status', value: 'No overtime rules configured' });
  }
  rows.push({ field: '', value: '' }); // spacer

  // ── Section: Holiday Calendar ──
  rows.push({ field: '── HOLIDAY CALENDAR ──', value: '' });
  if (dataset.holidayList.length > 0) {
    for (const h of dataset.holidayList) {
      rows.push({ field: `${h.date} — ${h.name}`, value: h.type });
    }
  } else {
    rows.push({ field: 'No holidays', value: 'in the report period' });
  }
  rows.push({ field: '', value: '' });

  // ── Section: Roster / Week Off ──
  rows.push({ field: '── ROSTER / WEEK OFF ──', value: '' });
  if (dataset.roster) {
    rows.push({ field: 'Roster Name', value: dataset.roster.name });
    rows.push({ field: 'Pattern', value: dataset.roster.pattern });
    rows.push({ field: 'Week Off 1', value: dataset.roster.weekOff1 ?? '—' });
    rows.push({ field: 'Week Off 2', value: dataset.roster.weekOff2 ?? '—' });
  } else {
    rows.push({ field: 'Status', value: 'No default roster configured' });
  }
  rows.push({ field: '', value: '' });

  // ── Section: Payroll Context ──
  rows.push({ field: '── PAYROLL CONTEXT ──', value: '' });
  if (dataset.payrollRun) {
    rows.push({ field: 'Payroll Run Status', value: dataset.payrollRun.status });
    rows.push({ field: 'Locked By', value: dataset.payrollRun.lockedBy ?? '—' });
    rows.push({ field: 'Locked At', value: dataset.payrollRun.lockedAt?.toLocaleString('en-IN') ?? '—' });
    rows.push({ field: 'Payroll Month', value: `${dataset.payrollRun.month}/${dataset.payrollRun.year}` });
  } else {
    rows.push({ field: 'Status', value: 'No payroll run for this period' });
  }

  return {
    name: 'Processing Metadata',
    columns,
    rows,
  };
}
