-- AlterTable
ALTER TABLE "ess_configs" ALTER COLUMN "attendanceRegularization" SET DEFAULT true,
ALTER COLUMN "reimbursementClaims" SET DEFAULT true,
ALTER COLUMN "profileUpdate" SET DEFAULT true,
ALTER COLUMN "documentUpload" SET DEFAULT true,
ALTER COLUMN "loanApplication" SET DEFAULT true,
ALTER COLUMN "assetView" SET DEFAULT true,
ALTER COLUMN "performanceGoals" SET DEFAULT true,
ALTER COLUMN "appraisalAccess" SET DEFAULT true,
ALTER COLUMN "feedback360" SET DEFAULT true,
ALTER COLUMN "trainingEnrollment" SET DEFAULT true,
ALTER COLUMN "helpDesk" SET DEFAULT true,
ALTER COLUMN "employeeDirectory" SET DEFAULT true,
ALTER COLUMN "policyDocuments" SET DEFAULT true,
ALTER COLUMN "grievanceSubmission" SET DEFAULT true,
ALTER COLUMN "announcementBoard" SET DEFAULT true,
ALTER COLUMN "leaveCancellation" SET DEFAULT true,
ALTER COLUMN "mobileOfflinePunch" SET DEFAULT true,
ALTER COLUMN "mssApproveAttendance" SET DEFAULT true,
ALTER COLUMN "mssApproveLeave" SET DEFAULT true,
ALTER COLUMN "mssViewTeam" SET DEFAULT true,
ALTER COLUMN "mssViewTeamAttendance" SET DEFAULT true,
ALTER COLUMN "shiftSwapRequest" SET DEFAULT true,
ALTER COLUMN "viewOrgChart" SET DEFAULT true,
ALTER COLUMN "viewSalaryStructure" SET DEFAULT true,
ALTER COLUMN "viewShiftSchedule" SET DEFAULT true,
ALTER COLUMN "wfhRequest" SET DEFAULT true;
