#!/usr/bin/env node

/**
 * merge-prisma.js
 *
 * Merges base.prisma + all module .prisma files into a single schema.prisma
 * that Prisma CLI can consume (generate, migrate, studio).
 *
 * Usage:
 *   node scripts/merge-prisma.js
 *
 * Structure:
 *   prisma/base.prisma           → generator + datasource blocks
 *   prisma/modules/**\/*.prisma   → domain-specific models & enums
 *   prisma/schema.prisma         → OUTPUT (auto-generated, do NOT edit)
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PRISMA_DIR = path.resolve(__dirname, '..', 'prisma');
const BASE_FILE = path.join(PRISMA_DIR, 'base.prisma');
const MODULES_DIR = path.join(PRISMA_DIR, 'modules');
const OUTPUT_FILE = path.join(PRISMA_DIR, 'schema.prisma');

// ── Helpers ──────────────────────────────────────────────

function collectPrismaFiles(dir) {
  const results = [];

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      results.push(...collectPrismaFiles(fullPath));
    } else if (entry.isFile() && entry.name.endsWith('.prisma')) {
      results.push(fullPath);
    }
  }

  return results.sort(); // deterministic ordering
}

function buildModuleLabel(filePath) {
  const relative = path.relative(MODULES_DIR, filePath);
  return relative.replace(/\.prisma$/, '').replace(/\\/g, '/');
}

// ── Validation ───────────────────────────────────────────

function validateNoDuplicates(moduleFiles) {
  const modelNames = new Map(); // name → source file
  const enumNames = new Map();
  const errors = [];

  for (const file of moduleFiles) {
    const content = fs.readFileSync(file, 'utf-8');
    const label = buildModuleLabel(file);

    // Match model definitions
    for (const match of content.matchAll(/^model\s+(\w+)\s*\{/gm)) {
      const name = match[1];
      if (modelNames.has(name)) {
        errors.push(`Duplicate model "${name}" in ${label} (already in ${modelNames.get(name)})`);
      } else {
        modelNames.set(name, label);
      }
    }

    // Match enum definitions
    for (const match of content.matchAll(/^enum\s+(\w+)\s*\{/gm)) {
      const name = match[1];
      if (enumNames.has(name)) {
        errors.push(`Duplicate enum "${name}" in ${label} (already in ${enumNames.get(name)})`);
      } else {
        enumNames.set(name, label);
      }
    }
  }

  return { errors, modelCount: modelNames.size, enumCount: enumNames.size };
}

// ── Main ─────────────────────────────────────────────────

function main() {
  console.log('🔧 Prisma Schema Merge');
  console.log('─'.repeat(50));

  // 1. Read base
  if (!fs.existsSync(BASE_FILE)) {
    console.error(`❌ Base file not found: ${BASE_FILE}`);
    process.exit(1);
  }
  const baseContent = fs.readFileSync(BASE_FILE, 'utf-8').trim();
  console.log(`✓ Base: ${path.relative(PRISMA_DIR, BASE_FILE)}`);

  // 2. Collect module files
  if (!fs.existsSync(MODULES_DIR)) {
    console.error(`❌ Modules directory not found: ${MODULES_DIR}`);
    process.exit(1);
  }
  const moduleFiles = collectPrismaFiles(MODULES_DIR);
  if (moduleFiles.length === 0) {
    console.error('❌ No .prisma files found in modules/');
    process.exit(1);
  }
  console.log(`✓ Found ${moduleFiles.length} module file(s)`);

  // 3. Validate no duplicates
  const { errors, modelCount, enumCount } = validateNoDuplicates(moduleFiles);
  if (errors.length > 0) {
    console.error('\n❌ Duplicate definitions found:');
    for (const err of errors) {
      console.error(`   - ${err}`);
    }
    process.exit(1);
  }
  console.log(`✓ ${modelCount} models, ${enumCount} enums (no duplicates)`);

  // 4. Merge
  const sections = [
    '// ╔══════════════════════════════════════════════════════════════╗',
    '// ║  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY           ║',
    '// ║  Edit files in prisma/modules/**/*.prisma instead          ║',
    '// ║  Then run: pnpm prisma:merge                               ║',
    `// ║  Generated: ${new Date().toISOString().slice(0, 19)}                    ║`,
    '// ╚══════════════════════════════════════════════════════════════╝',
    '',
    baseContent,
  ];

  for (const file of moduleFiles) {
    const label = buildModuleLabel(file);
    const content = fs.readFileSync(file, 'utf-8').trim();
    sections.push('');
    sections.push(`// ─── Module: ${label} ${'─'.repeat(Math.max(0, 45 - label.length))}`);
    sections.push('');
    sections.push(content);
  }

  // 5. Write output
  const output = sections.join('\n') + '\n';
  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

  const lineCount = output.split('\n').length;
  console.log(`✓ Output: schema.prisma (${lineCount} lines)`);
  console.log('─'.repeat(50));
  console.log('✅ Merge complete!');
}

main();
